// Generated by tools/build_assets.py from main.pak - do not edit by hand.
window.ENTITIES = [
 {
  "id": "sun",
  "name": "Sun",
  "mode": "plant",
  "goal": false,
  "tip": "The currency of the lawn.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "water",
  "name": "Water",
  "mode": "plant",
  "goal": false,
  "tip": "Wet. Good for growing.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "seed",
  "name": "Seed",
  "mode": "plant",
  "goal": false,
  "tip": "Every plant starts as a seed packet.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "dirt",
  "name": "Dirt",
  "mode": "plant",
  "goal": false,
  "tip": "Good, honest lawn dirt.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "sprout",
  "name": "Sprout",
  "mode": "plant",
  "goal": false,
  "tip": "A tiny plant, full of potential.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "night",
  "name": "Night",
  "mode": "plant",
  "goal": false,
  "tip": "When the sun goes under the dirt, the shrooms wake up.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "fire",
  "name": "Fire",
  "mode": "plant",
  "goal": false,
  "tip": "Hot hot hot.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "rock",
  "name": "Rock",
  "mode": "plant",
  "goal": false,
  "tip": "A pebble from the yard.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "ice",
  "name": "Ice",
  "mode": "plant",
  "goal": false,
  "tip": "Brrrr.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "pool",
  "name": "Pool",
  "mode": "plant",
  "goal": false,
  "tip": "The backyard pool.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "pea",
  "name": "Pea",
  "mode": "plant",
  "goal": false,
  "tip": "Ammunition.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "explosion",
  "name": "Explosion",
  "mode": "plant",
  "goal": false,
  "tip": "POW!!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "tree",
  "name": "Tree",
  "mode": "plant",
  "goal": false,
  "tip": "The Tree of Wisdom knows many things.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "grave",
  "name": "Grave",
  "mode": "plant",
  "goal": false,
  "tip": "Something is stirring underneath...",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "zombie_p",
  "name": "Zombie",
  "mode": "plant",
  "goal": false,
  "tip": "Brains!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "metal",
  "name": "Metal",
  "mode": "plant",
  "goal": false,
  "tip": "Shiny and magnetic.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "gold",
  "name": "Gold",
  "mode": "plant",
  "goal": false,
  "tip": "Bling!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "sand",
  "name": "Sand",
  "mode": "plant",
  "goal": false,
  "tip": "Tiny rocks.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "rain",
  "name": "Rain",
  "mode": "plant",
  "goal": false,
  "tip": "Water, but falling.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "wind",
  "name": "Wind",
  "mode": "plant",
  "goal": false,
  "tip": "Whoosh.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "star",
  "name": "Star",
  "mode": "plant",
  "goal": false,
  "tip": "Twinkle twinkle.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "lawn_mower",
  "name": "Lawn Mower",
  "mode": "plant",
  "goal": false,
  "tip": "The last line of defense.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "crazy_dave",
  "name": "Crazy Dave",
  "mode": "plant",
  "goal": false,
  "tip": "He's CRAZY!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "taco",
  "name": "Taco",
  "mode": "plant",
  "goal": false,
  "tip": "",
  "stats": [
   "What are you going to do with a taco?"
  ],
  "flavor": ""
 },
 {
  "id": "peashooter",
  "name": "Peashooter",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots peas at the enemy",
  "stats": [
   "Damage: normal"
  ],
  "flavor": "How can a single plant grow and shoot so many peas so quickly? Peashooter says, \"Hard work, commitment, and a healthy, well-balanced breakfast of sunlight and high-fiber carbon dioxide make it all possible.\""
 },
 {
  "id": "sunflower",
  "name": "Sunflower",
  "mode": "plant",
  "goal": true,
  "tip": "Gives you additional sun",
  "stats": [
   "Sun production: normal"
  ],
  "flavor": "Sunflower can't resist bouncing to the beat. Which beat is that? Why, the life-giving jazzy rhythm of the Earth itself, thumping at a frequency only Sunflower can hear."
 },
 {
  "id": "cherry_bomb",
  "name": "Cherry Bomb",
  "mode": "plant",
  "goal": true,
  "tip": "Blows up all zombies in an area",
  "stats": [
   "Damage: massive",
   "Range: all zombies in a medium area",
   "Usage: single use, instant"
  ],
  "flavor": "\"I wanna explode,\" says Cherry #1. \"No, let's detonate instead!\" says his brother, Cherry #2. After intense consultation they agree to explodonate."
 },
 {
  "id": "wall_nut",
  "name": "Wall-nut",
  "mode": "plant",
  "goal": true,
  "tip": "Blocks off zombies and protects your other plants",
  "stats": [
   "Toughness: high"
  ],
  "flavor": "\"People wonder how I feel about getting constantly chewed on by zombies,\" says Wall-nut. \"What they don't realize is that with my limited senses all I can feel is a kind of tingling, like a relaxing back rub.\""
 },
 {
  "id": "potato_mine",
  "name": "Potato Mine",
  "mode": "plant",
  "goal": true,
  "tip": "Explodes on contact, but takes time to arm itself",
  "stats": [
   "Damage: massive",
   "Range: all zombies in a small area",
   "Usage: single use, delayed activation"
  ],
  "flavor": "Some folks say Potato Mine is lazy, that he leaves everything to the last minute. Potato Mine says nothing. He's too busy thinking about his investment strategy."
 },
 {
  "id": "snow_pea",
  "name": "Snow Pea",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots frozen peas that damage and slow the enemy",
  "stats": [
   "Damage: normal, slows zombies"
  ],
  "flavor": "Folks often tell Snow Pea how \"cool\" he is, or exhort him to \"chill out.\" They tell him to \"stay frosty.\" Snow Pea just rolls his eyes. He's heard 'em all."
 },
 {
  "id": "chomper",
  "name": "Chomper",
  "mode": "plant",
  "goal": true,
  "tip": "Devours a zombie whole, but is vulnerable while chewing",
  "stats": [
   "Damage: massive",
   "Range: very short",
   "Special: long delay between chomps"
  ],
  "flavor": "Chomper almost got a gig doing stunts for The Little Shop of Horrors but it fell through when his agent demanded too much on the front end. Chomper's not resentful, though. He says it's just part of the business."
 },
 {
  "id": "repeater",
  "name": "Repeater",
  "mode": "plant",
  "goal": true,
  "tip": "Fires two peas at a time",
  "stats": [
   "Damage: normal (for each pea)",
   "Firing speed: 2x"
  ],
  "flavor": "Repeater is fierce. He's from the streets. He doesn't take attitude from anybody, plant or zombie, and he shoots peas to keep people at a distance. Secretly, though, Repeater yearns for love."
 },
 {
  "id": "puff_shroom",
  "name": "Puff-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots short-ranged spores at the enemy",
  "stats": [
   "Damage: normal",
   "Range: short",
   "Sleeps during the day"
  ],
  "flavor": "\"I only recently became aware of the existence of zombies,\" says Puff-shroom. \"Like many fungi, I'd just assumed they were fairy tales or movie monsters. This whole experience has been a huge eye-opener for me.\""
 },
 {
  "id": "sun_shroom",
  "name": "Sun-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Gives small sun at first and normal sun later",
  "stats": [
   "Sun production: low, then normal",
   "Sleeps during the day"
  ],
  "flavor": "Sun-shroom hates sun. He hates it so much that when it builds up in his system, he spits it out as fast as he can. He just won't abide it. To him, sun is crass."
 },
 {
  "id": "fume_shroom",
  "name": "Fume-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots fumes that can pass through screen doors",
  "stats": [
   "Damage: normal, penetrates screen doors",
   "Range: all zombies in the fume cloud",
   "Sleeps during the day"
  ],
  "flavor": "\"I was in a dead-end job producing yeast spores for a bakery,\" says Fume-shroom. \"Then Puff-shroom, bless 'im, told me about this great opportunity blasting zombies. Now I really feel like I'm making a difference.\""
 },
 {
  "id": "grave_buster",
  "name": "Grave Buster",
  "mode": "plant",
  "goal": true,
  "tip": "Plant it on a grave to remove the grave",
  "stats": [
   "Usage: single use, must be planted on graves",
   "Special: removes graves"
  ],
  "flavor": "Despite Grave Buster's fearsome appearance, he wants everyone to know that he loves kittens and spends his off hours volunteering at a local zombie rehabilitation center. \"It's just the right thing to do,\" he says."
 },
 {
  "id": "hypno_shroom",
  "name": "Hypno-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Makes a zombie fight for you",
  "stats": [
   "Usage: single use, on contact",
   "Special: makes a zombie fight for you",
   "Sleeps during the day"
  ],
  "flavor": "\"Zombies are our friends,\" asserts Hypno-shroom. \"They're badly misunderstood creatures who play a valuable role in our ecology. We can and should do more to bring them round to our way of thinking.\""
 },
 {
  "id": "scaredy_shroom",
  "name": "Scaredy-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Long-ranged shooter that hides when enemies get near it",
  "stats": [
   "Damage: normal",
   "Special: stops shooting when enemy is close",
   "Sleeps during the day"
  ],
  "flavor": "\"Who's there?\" whispers Scaredy-shroom, voice barely audible. \"Go away. I don't want to see anybody. Unless it's the man from the circus.\""
 },
 {
  "id": "ice_shroom",
  "name": "Ice-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Temporarily immobilizes all zombies on the screen",
  "stats": [
   "Damage: very light, immobilizes zombies",
   "Range: all zombies on the screen",
   "Usage: single use, instant",
   "Sleeps during the day"
  ],
  "flavor": "Ice-shroom frowns, not because he's unhappy or because he disapproves, but because of a childhood injury that left his facial nerves paralyzed."
 },
 {
  "id": "doom_shroom",
  "name": "Doom-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Destroys a large area, leaving a crater in its wake",
  "stats": [
   "Damage: massive",
   "Range: all zombies in a huge area",
   "Usage: single use, instant",
   "Special: leaves a crater",
   "Sleeps during the day"
  ],
  "flavor": "\"You're lucky I'm on your side,\" says Doom-shroom. \"I could destroy everything you hold dear. It wouldn't be hard.\""
 },
 {
  "id": "lily_pad",
  "name": "Lily Pad",
  "mode": "plant",
  "goal": true,
  "tip": "Lets you plant non-aquatic plants on top of it",
  "stats": [
   "Special: non-aquatic plants can be planted on top of it",
   "Must be planted in water"
  ],
  "flavor": "Lily Pad never complains. Lily Pad never wants to know what's going on. Put a plant on top of Lily Pad, he won't say a thing. Does he have startling opinions or shocking secrets? Nobody knows. Lily Pad keeps it all inside."
 },
 {
  "id": "squash",
  "name": "Squash",
  "mode": "plant",
  "goal": true,
  "tip": "Squashes zombies",
  "stats": [
   "Damage: massive",
   "Range: short range, hits all zombies that it lands on",
   "Usage: single use"
  ],
  "flavor": "\"I'm ready!\" yells Squash. \"Let's do it! Put me in! There's nobody better! I'm your guy! C'mon! Whaddya waiting for? I need this!\""
 },
 {
  "id": "threepeater",
  "name": "Threepeater",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots peas in three lanes",
  "stats": [
   "Damage: normal (for each pea)",
   "Range: three lanes"
  ],
  "flavor": "Threepeater likes reading, backgammon and long periods of immobility in the park. Threepeater enjoys going to shows, particularly modern jazz. \"I'm just looking for that special someone,\" he says. Threepeater's favorite number is 5."
 },
 {
  "id": "tangle_kelp",
  "name": "Tangle Kelp",
  "mode": "plant",
  "goal": true,
  "tip": "Aquatic plant that pulls a zombie underwater",
  "stats": [
   "Damage: massive",
   "Usage: single use, on contact",
   "Must be planted in water"
  ],
  "flavor": "\"I'm totally invisible,\" Tangle Kelp thinks to himself. \"I'll hide here just below the surface and nobody will see me.\" His friends tell him they can see him perfectly well, but he'll never change."
 },
 {
  "id": "jalapeno",
  "name": "Jalapeno",
  "mode": "plant",
  "goal": true,
  "tip": "Destroys an entire lane of zombies",
  "stats": [
   "Damage: massive",
   "Range: all zombies in a lane",
   "Usage: single use, instant"
  ],
  "flavor": "\"NNNNNGGGGGG!!!!!!!!\" Jalapeno says. He's not going to explode, not this time. But soon. Oh, so soon. It's close. He knows it, he can feel it, his whole life's been leading up to this moment."
 },
 {
  "id": "spikeweed",
  "name": "Spikeweed",
  "mode": "plant",
  "goal": true,
  "tip": "Pops tires and hurts zombies that step on it",
  "stats": [
   "Damage: normal",
   "Range: all zombies that walk over it",
   "Special: can't be eaten by zombies"
  ],
  "flavor": "Hockey is Spikeweed's obsession. He's got box seat season tickets. He keeps close track of his favorite players. And he consistently cleans up in the office hockey pool. Just one problem: he's terrified of pucks."
 },
 {
  "id": "torchwood",
  "name": "Torchwood",
  "mode": "plant",
  "goal": true,
  "tip": "Peas that pass through it turn into fireballs",
  "stats": [
   "Special: doubles the damage of peas that pass through it.  Fireballs deal damage to nearby zombies on impact"
  ],
  "flavor": "Everybody likes and respects Torchwood. They like him for his integrity, for his steadfast friendship, for his ability to greatly maximize pea damage. But Torchwood has a secret: he can't read."
 },
 {
  "id": "tall_nut",
  "name": "Tall-nut",
  "mode": "plant",
  "goal": true,
  "tip": "Heavy-duty wall that can't be vaulted over",
  "stats": [
   "Toughness: very high",
   "Special: can't be vaulted or jumped over"
  ],
  "flavor": "People wonder if there's a rivalry between Wall-nut and Tall-nut. Tall-nut laughs a rich, baritone laugh. \"How could there be anything between us? We are brothers. If you knew what Wall-nut has done for me...\" Tall-nut's voice trails off and he smiles knowingly."
 },
 {
  "id": "sea_shroom",
  "name": "Sea-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Aquatic plant that shoots short-ranged spores",
  "stats": [
   "Damage: normal",
   "Range: short",
   "Must be planted in water",
   "Sleeps during the day"
  ],
  "flavor": "Sea-shroom has never seen the sea. It's in his name, he's heard loads about it, but he's just never found the time. One day, though, it'll go down."
 },
 {
  "id": "plantern",
  "name": "Plantern",
  "mode": "plant",
  "goal": true,
  "tip": "Lights up an area, letting you see through fog",
  "stats": [
   "Range: one lane",
   "Special: lets you see through fog"
  ],
  "flavor": "Plantern defies science. He just does. Other plants eat light and excrete oxygen; Plantern eats darkness and excretes light. Plantern's cagey about how he does it. \"I'm not gonna say 'sorcery,' I wouldn't use the term 'dark forces,' I just... I think I've said enough.\""
 },
 {
  "id": "cactus",
  "name": "Cactus",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots spikes that can pop balloons",
  "stats": [
   "Damage: normal",
   "Range: ground and air"
  ],
  "flavor": "She's prickly, sure, but Cactus's spikes belie a spongy heart filled with love and goodwill. She just wants to hug and be hugged. Most folks can't hang with that, but Cactus doesn't mind. She's been seeing an armadillo for a while and it really seems to be working out."
 },
 {
  "id": "blover",
  "name": "Blover",
  "mode": "plant",
  "goal": true,
  "tip": "Blows away all balloon zombies and fog",
  "stats": [
   "Usage: single use, instant",
   "Special: blows away all balloon zombies"
  ],
  "flavor": "When Blover was five he got a shiny new birthday cake. Blover made his wish, huffed and puffed, but was able to extinguish only 60% of the candles. Instead of giving up, though, he's used that early defeat as a catalyst to push himself harder ever since."
 },
 {
  "id": "split_pea",
  "name": "Split Pea",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots peas forward and backwards",
  "stats": [
   "Damage: normal",
   "Range: forward and backwards",
   "Firing Speed: 1x forward, 2x backwards"
  ],
  "flavor": "\"Yeah, I'm a Gemini,\" says Split Pea. \"I know, big surprise. But having two heads --or really, one head with a large head-like growth on the back-- pays off big in my line of work.\""
 },
 {
  "id": "starfruit",
  "name": "Starfruit",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots stars in 5 directions",
  "stats": [
   "Damage: normal",
   "Range: 5 directions"
  ],
  "flavor": "\"Aw, man,\" says Starfruit. \"I went to the dentist the other day and he said I have four cavities. I've got --count it-- ONE tooth! Four cavities in one tooth? How does this happen?\""
 },
 {
  "id": "pumpkin",
  "name": "Pumpkin",
  "mode": "plant",
  "goal": true,
  "tip": "Protects plants that are within its shell",
  "stats": [
   "Toughness: high",
   "Special: can be planted over another plant"
  ],
  "flavor": "Pumpkin hasn't heard from his cousin Renfield lately. Apparently Renfield's a big star, some kind of... what was it... sports hero? Peggle Master? Pumpkin doesn't really get it. He just does his job."
 },
 {
  "id": "magnet_shroom",
  "name": "Magnet-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Removes helmets and other metal objects from zombies",
  "stats": [
   "Range: nearby zombies",
   "Special: removes metal objects from zombies",
   "Sleeps during the day"
  ],
  "flavor": "Magnetism is a powerful force. Very powerful. Sometimes it scares Magnet-shroom a little. He's not sure if he can handle that kind of responsibility."
 },
 {
  "id": "cabbage_pult",
  "name": "Cabbage-pult",
  "mode": "plant",
  "goal": true,
  "tip": "Hurls cabbages at the enemy",
  "stats": [
   "Damage: normal",
   "Range: lobbed"
  ],
  "flavor": "Cabbage-pult is okay with launching cabbages at zombies. It's what he's paid for, after all, and he's good at it. He just doesn't understand how the zombies get up on the roof in the first place."
 },
 {
  "id": "flower_pot",
  "name": "Flower Pot",
  "mode": "plant",
  "goal": true,
  "tip": "Lets you plant on the roof",
  "stats": [
   "Special: allows you to plant on the roof"
  ],
  "flavor": "\"I'm a pot for planting. Yet I'm also a plant. HAS YOUR MIND EXPLODED YET?\""
 },
 {
  "id": "kernel_pult",
  "name": "Kernel-pult",
  "mode": "plant",
  "goal": true,
  "tip": "Flings corn kernels and butter at zombies",
  "stats": [
   "Damage: light (kernel), normal (butter)",
   "Range: lobbed",
   "Special: butter immobilizes zombies"
  ],
  "flavor": "Kernel-Pult is the eldest of the Pult brothers. Of the three of them, Kernel is the only one who consistently remembers the others' birthdays. He bugs them about it a little, too."
 },
 {
  "id": "coffee_bean",
  "name": "Coffee Bean",
  "mode": "plant",
  "goal": true,
  "tip": "Plant it on a mushroom to wake it up",
  "stats": [
   "Usage: single use, instant",
   "Special: can be planted over another plant, wakes up mushrooms"
  ],
  "flavor": "\"Hey, guys, hey!\" says Coffee Bean. \"Hey! What's up? Who's that? Hey! Didja see that thing? What thing? Whoa! Lions!\" Yep, Coffee Bean sure does get excited."
 },
 {
  "id": "garlic",
  "name": "Garlic",
  "mode": "plant",
  "goal": true,
  "tip": "Diverts zombies into other lanes",
  "stats": [
   "Usage: on contact",
   "Special: diverts zombies into other lanes"
  ],
  "flavor": "Lane-diversion isn't just Garlic's profession. It's his passion. He carries an advanced Doctorate in Redirection from the Brussels University. He'll talk all day about lane vectors and repulse arrays. He even pushes things into alternate avenues at home. Somehow his wife puts up with it."
 },
 {
  "id": "umbrella_leaf",
  "name": "Umbrella Leaf",
  "mode": "plant",
  "goal": true,
  "tip": "Protects nearby plants from bungees and catapults",
  "stats": [
   "Special: protects adjacent plants from bungees and catapults"
  ],
  "flavor": "\"SPROING!\" says Umbrella Leaf. \"Didja like that? I can do it again. SPROING! Woo! That's me popping up to protect stuff around me. Yeah. Just like that. EXACTLY like that. Believe it.\""
 },
 {
  "id": "marigold",
  "name": "Marigold",
  "mode": "plant",
  "goal": true,
  "tip": "Gives you silver and gold coins",
  "stats": [
   "Special: gives coins"
  ],
  "flavor": "Marigold spends a lot of time deciding whether to spit out a silver coin or a gold one. She thinks about it, weighs the angles. She does solid research and keeps up with current publications. That's how winners stay ahead."
 },
 {
  "id": "melon_pult",
  "name": "Melon-pult",
  "mode": "plant",
  "goal": true,
  "tip": "Does heavy damage to groups of zombies",
  "stats": [
   "Damage: heavy",
   "Range: lobbed",
   "Special: melons damage nearby enemies on impact"
  ],
  "flavor": "There's no false modesty with Melon-pult. \"Sun-for-damage, I deliver the biggest punch on the lawn,\" he says. \"I'm not bragging. Run the numbers. You'll see.\""
 },
 {
  "id": "gatling_pea",
  "name": "Gatling Pea",
  "mode": "plant",
  "goal": true,
  "tip": "Shoots four peas at a time\n(requires repeater)",
  "stats": [
   "Damage: normal (for each pea)",
   "Firing Speed: 4x",
   "Must be planted on repeaters"
  ],
  "flavor": "Gatling Pea's parents were concerned when he announced his intention to join the military. \"But honey, it's so dangerous!\" they said in unison. Gatling Pea refused to budge. \"Life is dangerous,\" he replied, eyes glinting with steely conviction."
 },
 {
  "id": "twin_sunflower",
  "name": "Twin Sunflower",
  "mode": "plant",
  "goal": true,
  "tip": "Gives twice as much sun as a sunflower\n(requires sunflower)",
  "stats": [
   "Sun production: double",
   "Must be planted on sunflowers"
  ],
  "flavor": "It was a crazed night of forbidden science that brought Twin Sunflower into existence. Thunder crashed overhead, strange lights flickered, even the very roaring wind seemed to hiss its angry denial. But to no avail. Twin Sunflower was alive, ALIVE!"
 },
 {
  "id": "gloom_shroom",
  "name": "Gloom-shroom",
  "mode": "plant",
  "goal": true,
  "tip": "Releases heavy fumes in an area around itself\n(requires fume-shroom)",
  "stats": [
   "Must be planted on fume-shrooms"
  ],
  "flavor": "\"I've always enjoyed releasing heavy fumes,\" says Gloom Shroom. \"I know a lot of people aren't cool with that. They say it's rude or that it smells bad. All I can say is, would you rather have your brain eaten by zombies?\""
 },
 {
  "id": "cattail",
  "name": "Cattail",
  "mode": "plant",
  "goal": true,
  "tip": "Attacks any lane and shoots down balloon zombies\n(requires lily pad)",
  "stats": [
   "Must be planted on lily pads"
  ],
  "flavor": "\"Woof!\" says Cattail. \"Woof woof woof! Does this confuse you? Do you expect me to say 'Meow' like a cat just because the word 'cat' is in my name and I also look like a cat? That's not how things work around here. I refuse to be pigeonholed.\""
 },
 {
  "id": "winter_melon",
  "name": "Winter Melon",
  "mode": "plant",
  "goal": true,
  "tip": "Does heavy damage and slows groups of zombies\n(requires melon-pult)",
  "stats": [
   "Damage: very heavy",
   "Range: lobbed",
   "Firing Speed: 1/2x",
   "Special: melons damage and freeze nearby enemies on impact",
   "Must be planted on melon-pults"
  ],
  "flavor": "Winter Melon tries to calm his nerves. He hears the zombies approach. Will he make it? Will anyone make it?"
 },
 {
  "id": "gold_magnet",
  "name": "Gold Magnet",
  "mode": "plant",
  "goal": true,
  "tip": "Collects coins and diamonds for you\n(requires magnet-shroom)",
  "stats": [
   "Must be planted on magnet-shrooms"
  ],
  "flavor": "\"How did I end up here?\" asks Gold Magnet. \"I was on the fast track --corner office, full benefits, stock options. I was gonna be Vice President of Midwestern Operations. Now I'm here, on this lawn, in serious danger of being eaten to death. Ooh! A coin!\""
 },
 {
  "id": "spikerock",
  "name": "Spikerock",
  "mode": "plant",
  "goal": true,
  "tip": "Pops multiple tires and damages zombies that walk over it\n(requires spikeweed)",
  "stats": [
   "Must be planted on spikeweeds"
  ],
  "flavor": "Spikerock just got back from a trip to Europe. He had a great time, met some wonderful people, really broadened his horizons. He never knew they made museums so big, or put so many paintings in them. That was a big surprise for him."
 },
 {
  "id": "cob_cannon",
  "name": "Cob Cannon",
  "mode": "plant",
  "goal": true,
  "tip": "Click to launch deadly cobs of corn\n(requires 2 kernel-pults)",
  "stats": [
   "Must be planted on 2 side-by-side kernel-pults"
  ],
  "flavor": "What's the deal with Cob Cannon, anyway?  He went to Harvard. He practices law in a prestigious New York firm. He can explode whole areas of zombies with a single corn-launch. All this is common knowledge. But deep inside, what really makes him tick?"
 },
 {
  "id": "imitater",
  "name": "Imitater",
  "mode": "plant",
  "goal": true,
  "tip": "Lets you have two of the same plant",
  "stats": [],
  "flavor": "\"I remember the Zombie Wars back in '76,\" says Imitater in a raspy, old-man's voice. \"Back then, we didn't have all these fancy peashooters and jalapenos. All we had was guts. Guts and a spoon.\""
 },
 {
  "id": "z_zombie",
  "name": "Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low"
  ],
  "flavor": "This zombie loves brains. Can't get enough. Brains, brains, brains, day in and night out. Old and stinky brains? Rotten brains? Brains clearly past their prime? Doesn't matter. Regular zombie wants 'em."
 },
 {
  "id": "brain",
  "name": "Brain",
  "mode": "zombie",
  "goal": false,
  "tip": "Delicious.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "z_grave",
  "name": "Grave",
  "mode": "zombie",
  "goal": false,
  "tip": "Home sweet home.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "junk",
  "name": "Junk",
  "mode": "zombie",
  "goal": false,
  "tip": "One zombie's trash is another zombie's armor.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "z_water",
  "name": "Water",
  "mode": "zombie",
  "goal": false,
  "tip": "Zombies can swim. Sort of.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "z_metal",
  "name": "Metal",
  "mode": "zombie",
  "goal": false,
  "tip": "Heavy and shiny.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "z_night",
  "name": "Night",
  "mode": "zombie",
  "goal": false,
  "tip": "The best time to shamble.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "z_ice",
  "name": "Ice",
  "mode": "zombie",
  "goal": false,
  "tip": "Frozen solid.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "traffic_cone",
  "name": "Traffic Cone",
  "mode": "zombie",
  "goal": false,
  "tip": "Found on the side of the road.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "bucket",
  "name": "Bucket",
  "mode": "zombie",
  "goal": false,
  "tip": "Makes a great hat.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "newspaper",
  "name": "Newspaper",
  "mode": "zombie",
  "goal": false,
  "tip": "Read all about it!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "screen_door",
  "name": "Screen Door",
  "mode": "zombie",
  "goal": false,
  "tip": "A sturdy shield.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "football_helmet",
  "name": "Football Helmet",
  "mode": "zombie",
  "goal": false,
  "tip": "Protects the brain.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "pole",
  "name": "Pole",
  "mode": "zombie",
  "goal": false,
  "tip": "Long and pointy.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "ladder",
  "name": "Ladder",
  "mode": "zombie",
  "goal": false,
  "tip": "Over the wall!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "pogo_stick",
  "name": "Pogo Stick",
  "mode": "zombie",
  "goal": false,
  "tip": "Boing boing boing.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "pickaxe",
  "name": "Pickaxe",
  "mode": "zombie",
  "goal": false,
  "tip": "For digging.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "flag",
  "name": "Flag",
  "mode": "zombie",
  "goal": false,
  "tip": "A huge wave of zombies is approaching!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "ducky_tube",
  "name": "Ducky Tube",
  "mode": "zombie",
  "goal": false,
  "tip": "Quack.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "dolphin",
  "name": "Dolphin",
  "mode": "zombie",
  "goal": false,
  "tip": "Smart and slippery.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "music",
  "name": "Music",
  "mode": "zombie",
  "goal": false,
  "tip": "Thriller night!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "jack_in_the_box",
  "name": "Jack-in-the-Box",
  "mode": "zombie",
  "goal": false,
  "tip": "Pop goes the weasel...",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "balloon",
  "name": "Balloon",
  "mode": "zombie",
  "goal": false,
  "tip": "Up, up and away!",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "bungee_cord",
  "name": "Bungee Cord",
  "mode": "zombie",
  "goal": false,
  "tip": "Stretchy.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "vehicle",
  "name": "Vehicle",
  "mode": "zombie",
  "goal": false,
  "tip": "Zombies love a road trip.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "horde",
  "name": "Horde",
  "mode": "zombie",
  "goal": false,
  "tip": "Zombies, zombies everywhere.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "big_brain",
  "name": "Big Brain",
  "mode": "zombie",
  "goal": false,
  "tip": "A genius-level brain.",
  "stats": [],
  "flavor": ""
 },
 {
  "id": "flag_zombie",
  "name": "Flag Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low"
  ],
  "flavor": "Make no mistake, Flag Zombie loves brains. But somewhere down the line he also picked up a fascination with flags. Maybe it's because the flags always have brains on them. Hard to say."
 },
 {
  "id": "conehead",
  "name": "Conehead Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium"
  ],
  "flavor": "Conehead Zombie shuffled mindlessly forward like every other zombie. But something made him stop, made him pick up a traffic cone and stick it on his head. Oh yeah. He likes to party."
 },
 {
  "id": "buckethead",
  "name": "Buckethead Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: high",
   "Weakness: magnet-shroom"
  ],
  "flavor": "Buckethead Zombie always wore a bucket. Part of it was to assert his uniqueness in an uncaring world. Mostly he just forgot it was there in the first place."
 },
 {
  "id": "pole_vaulting",
  "name": "Pole Vaulting Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Speed: fast, then normal (after jump)",
   "Special: jumps the first plant he runs into"
  ],
  "flavor": "Some zombies take it further, aspire more, push themselves beyond the normal into greatness. That's Pole Vaulting Zombie right there. That is so him."
 },
 {
  "id": "newspaper_zombie",
  "name": "Newspaper Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low",
   "Newspaper Toughness: low",
   "Speed: normal, then fast (after losing newspaper)"
  ],
  "flavor": "Newspaper Zombie was *this* close to finishing his sudoku puzzle. No wonder he's freaking out."
 },
 {
  "id": "screen_door_zombie",
  "name": "Screen Door Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low",
   "Screen Door Toughness: high",
   "Weakness: fume-shroom",
   "and magnet-shroom"
  ],
  "flavor": "He got his screen door from the last inexpertly defended home he visited, after he ATE THE HOMEOWNER'S BRAINS."
 },
 {
  "id": "football_zombie",
  "name": "Football Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: very high",
   "Speed: fast",
   "Weakness: magnet-shroom"
  ],
  "flavor": "Football Zombie gives 110 percent whenever he's on the field. He's a team player who delivers both offensively and defensively. He has no idea what a football is."
 },
 {
  "id": "dancing_zombie",
  "name": "Dancing Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Special: summons back-up dancers"
  ],
  "flavor": "Dancing Zombie's latest album, \"GrarrBRAINSarblarbl,\" is already rocketing up the undead charts."
 },
 {
  "id": "backup_dancer",
  "name": "Backup Dancer",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low"
  ],
  "flavor": "Backup Dancer Zombie spent six years perfecting his art at the Chewliard Performing Arts School in Zombie New York City."
 },
 {
  "id": "ducky_tube_zombie",
  "name": "Ducky Tube Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low",
   "Only appears in the pool"
  ],
  "flavor": "It takes a certain kind of zombie to be a Ducky Tuber. Not every zombie can handle it. Some crack. They can't take it. They walk away and give up on brains forever."
 },
 {
  "id": "snorkel_zombie",
  "name": "Snorkel Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low",
   "Special: submerges to avoid attacks",
   "Only appears in the pool"
  ],
  "flavor": "Zombies don't breathe. They don't need air. So why does Snorkel Zombie need a snorkel to swim underwater?"
 },
 {
  "id": "zomboni",
  "name": "Zomboni",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: high",
   "Special: crushes plants, leaves an ice trail"
  ],
  "flavor": "Not to be mistaken for a Zamboni® brand ice resurfacing machine.  Zamboni® and the image of the ice-resurfacing machine are registered trademarks of Frank J. Zamboni & Co., Inc., and \"Zomboni\" is used with permission.  For all your non-zombie-related ice resurfacing needs, visit www.zamboni.com!"
 },
 {
  "id": "bobsled_team",
  "name": "Zombie Bobsled Team",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low (each zombie)",
   "Bobsled Toughness: low",
   "Special: only appears on ice"
  ],
  "flavor": "Zombie Bobsled Team worked hard to get where they are. They live together, eat brains together and train together to become a cohesive zombie unit."
 },
 {
  "id": "dolphin_rider",
  "name": "Dolphin Rider Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Speed: fast, then slow (after jump)",
   "Special: jumps over the first plant he runs into",
   "Only appears in the pool"
  ],
  "flavor": "The dolphin is also a zombie."
 },
 {
  "id": "jack_zombie",
  "name": "Jack-in-the-Box Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Speed: fast",
   "Special: jack-in-the-box explodes",
   "Weakness: magnet-shroom"
  ],
  "flavor": "This zombie shivers, not because he's cold but because he's crazy."
 },
 {
  "id": "balloon_zombie",
  "name": "Balloon Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low",
   "Special: flying",
   "Weakness: cactus and blover"
  ],
  "flavor": "Balloon Zombie really lucked out. The balloon thing really works and none of the other zombies have picked up on it."
 },
 {
  "id": "digger_zombie",
  "name": "Digger Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Speed: fast, then slow",
   "Special: tunnels underground and appears on the left side of the lawn",
   "Weakness: split pea",
   "and magnet-shroom"
  ],
  "flavor": "Digger Zombie spends three days a week getting his excavation permits in order."
 },
 {
  "id": "pogo_zombie",
  "name": "Pogo Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Special: hops over plants",
   "Weakness: magnet-shroom"
  ],
  "flavor": "Sproing! Sproing! Sproing! That's the sound of a powerful and effective zombie doing what he does best."
 },
 {
  "id": "zombie_yeti",
  "name": "Zombie Yeti",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: high",
   "Special: runs away after a short while"
  ],
  "flavor": "Little is known about the Zombie Yeti other than his name, birth date, social security number, educational history, past work experience and sandwich preference (roast beef and Swiss)."
 },
 {
  "id": "bungee_zombie",
  "name": "Bungee Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Special: descends from the sky and steals a plant"
  ],
  "flavor": "Bungee Zombie loves to take risks. After all, what's the point of being dead if you don't live a little?"
 },
 {
  "id": "ladder_zombie",
  "name": "Ladder Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Ladder Toughness: medium",
   "Speed: fast, then slow (after placing ladder)",
   "Weakness: fume-shroom",
   "and magnet-shroom"
  ],
  "flavor": "He picked the ladder up for $8.99."
 },
 {
  "id": "catapult_zombie",
  "name": "Catapult Zombie",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: medium",
   "Special: lobs basketballs at your plants"
  ],
  "flavor": "Of all the things Catapult Zombie could launch with his catapult, basketballs seemed like the best and most obvious choice."
 },
 {
  "id": "gargantuar",
  "name": "Gargantuar",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: extremely high"
  ],
  "flavor": "When Gargantuar walks, the earth trembles. When he moans, other zombies fall silent. He is the zombie other zombies dream they could be. But he still can't find a girlfriend."
 },
 {
  "id": "imp",
  "name": "Imp",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness: low"
  ],
  "flavor": "Imp may be small, but he's wiry. He's proficient in zombie judo, zombie karate and zombie bare-knuckle brawling. He also plays the melodica."
 },
 {
  "id": "dr_zomboss",
  "name": "Dr. Zomboss",
  "mode": "zombie",
  "goal": true,
  "tip": "",
  "stats": [
   "Toughness (in Zombot shell): extreme"
  ],
  "flavor": "Edgar George Zomboss achieved his Doctorate in Thanatology in only two years. Quickly mastering thanatological technology, he built his fearsome Zombot and set about establishing absolute dominance of his local subdivision."
 }
];
