// Hand-made recipes: [ingredient A, ingredient B, result]. Order of A/B doesn't matter.
// Any pair that isn't listed here still works: the game invents a "hybrid" for it.
window.MODES = {
  plant: {
    title: 'Plant Mode',
    noun: 'Plants',
    start: ['sun', 'water', 'seed', 'dirt'],
    background: 'assets/images/background1.jpg',
    sounds: { combine: ['plant', 'plant2'], discover: 'seedlift', goal: 'achievement', win: 'prize' },
    adjectives: ['Mega', 'Spicy', 'Frozen', 'Giant', 'Tiny', 'Twin', 'Golden', 'Sleepy', 'Angry', 'Royal', 'Shiny', 'Wild'],
    recipes: [
      // ---- elements
      ['seed', 'water', 'sprout'],
      ['seed', 'dirt', 'sprout'],
      ['sun', 'dirt', 'night'],
      ['dirt', 'dirt', 'rock'],
      ['sun', 'sun', 'fire'],
      ['water', 'water', 'pool'],
      ['water', 'night', 'ice'],
      ['sun', 'water', 'rain'],
      ['rain', 'rain', 'wind'],
      ['rain', 'night', 'wind'],
      ['night', 'night', 'star'],
      ['sun', 'night', 'star'],
      ['fire', 'fire', 'explosion'],
      ['fire', 'rock', 'metal'],
      ['metal', 'sun', 'gold'],
      ['rock', 'water', 'sand'],
      ['rock', 'wind', 'sand'],
      ['sprout', 'sprout', 'tree'],
      ['sprout', 'water', 'tree'],
      ['night', 'rock', 'grave'],
      ['grave', 'dirt', 'zombie_p'],
      ['grave', 'night', 'zombie_p'],
      ['sprout', 'seed', 'pea'],
      ['metal', 'sprout', 'lawn_mower'],
      ['flower_pot', 'zombie_p', 'crazy_dave'],
      ['crazy_dave', 'fire', 'taco'],
      // ---- day
      ['sprout', 'sun', 'sunflower'],
      ['pea', 'sprout', 'peashooter'],
      ['pea', 'seed', 'peashooter'],
      ['peashooter', 'pea', 'repeater'],
      ['peashooter', 'peashooter', 'repeater'],
      ['sprout', 'rock', 'wall_nut'],
      ['explosion', 'sprout', 'cherry_bomb'],
      ['explosion', 'seed', 'cherry_bomb'],
      ['explosion', 'dirt', 'potato_mine'],
      ['peashooter', 'ice', 'snow_pea'],
      ['zombie_p', 'sprout', 'chomper'],
      // ---- night
      ['sprout', 'night', 'puff_shroom'],
      ['puff_shroom', 'sun', 'sun_shroom'],
      ['puff_shroom', 'puff_shroom', 'fume_shroom'],
      ['puff_shroom', 'wind', 'fume_shroom'],
      ['grave', 'sprout', 'grave_buster'],
      ['puff_shroom', 'zombie_p', 'hypno_shroom'],
      ['puff_shroom', 'night', 'scaredy_shroom'],
      ['puff_shroom', 'ice', 'ice_shroom'],
      ['puff_shroom', 'explosion', 'doom_shroom'],
      // ---- pool
      ['pool', 'sprout', 'lily_pad'],
      ['wall_nut', 'night', 'pumpkin'],
      ['pumpkin', 'rock', 'squash'],
      ['wall_nut', 'explosion', 'squash'],
      ['repeater', 'pea', 'threepeater'],
      ['repeater', 'peashooter', 'threepeater'],
      ['lily_pad', 'water', 'tangle_kelp'],
      ['pool', 'zombie_p', 'tangle_kelp'],
      ['fire', 'sprout', 'jalapeno'],
      ['sand', 'sprout', 'cactus'],
      ['cactus', 'dirt', 'spikeweed'],
      ['fire', 'tree', 'torchwood'],
      ['wall_nut', 'wall_nut', 'tall_nut'],
      ['wall_nut', 'tree', 'tall_nut'],
      // ---- fog
      ['puff_shroom', 'pool', 'sea_shroom'],
      ['puff_shroom', 'water', 'sea_shroom'],
      ['fire', 'night', 'plantern'],
      ['star', 'sprout', 'starfruit'],
      ['wind', 'sprout', 'blover'],
      ['peashooter', 'wind', 'split_pea'],
      ['puff_shroom', 'metal', 'magnet_shroom'],
      // ---- roof
      ['tree', 'rock', 'cabbage_pult'],
      ['sprout', 'dirt', 'flower_pot'],
      ['cabbage_pult', 'sun', 'kernel_pult'],
      ['fire', 'seed', 'coffee_bean'],
      ['night', 'seed', 'garlic'],
      ['rain', 'sprout', 'umbrella_leaf'],
      ['gold', 'sprout', 'marigold'],
      ['cabbage_pult', 'water', 'melon_pult'],
      // ---- upgrades
      ['repeater', 'metal', 'gatling_pea'],
      ['repeater', 'repeater', 'gatling_pea'],
      ['sunflower', 'sunflower', 'twin_sunflower'],
      ['fume_shroom', 'fume_shroom', 'gloom_shroom'],
      ['lily_pad', 'cactus', 'cattail'],
      ['melon_pult', 'ice', 'winter_melon'],
      ['magnet_shroom', 'gold', 'gold_magnet'],
      ['spikeweed', 'rock', 'spikerock'],
      ['spikeweed', 'metal', 'spikerock'],
      ['kernel_pult', 'kernel_pult', 'cob_cannon'],
      ['seed', 'seed', 'imitater'],
    ],
  },

  zombie: {
    title: 'Zombie Mode',
    noun: 'Zombies',
    start: ['z_zombie', 'brain', 'z_grave', 'junk', 'z_water'],
    background: 'assets/images/background2.jpg',
    sounds: { combine: ['groan', 'groan2', 'groan3', 'groan4'], discover: 'gravebutton', goal: 'evillaugh', win: 'hugewave' },
    adjectives: ['Undead', 'Rotten', 'Mega', 'Giga', 'Disco', 'Frozen', 'Armored', 'Hungry', 'Screaming', 'Royal', 'Smelly', 'Headless'],
    recipes: [
      // ---- elements
      ['junk', 'junk', 'z_metal'],
      ['junk', 'z_water', 'ducky_tube'],
      ['junk', 'z_grave', 'traffic_cone'],
      ['junk', 'brain', 'newspaper'],
      ['z_metal', 'junk', 'bucket'],
      ['z_metal', 'z_grave', 'screen_door'],
      ['z_metal', 'brain', 'football_helmet'],
      ['z_metal', 'z_metal', 'pole'],
      ['pole', 'z_metal', 'vehicle'],
      ['pole', 'pole', 'ladder'],
      ['pole', 'junk', 'pogo_stick'],
      ['pole', 'z_grave', 'pickaxe'],
      ['pole', 'ducky_tube', 'bungee_cord'],
      ['z_grave', 'z_grave', 'z_night'],
      ['z_water', 'z_night', 'z_ice'],
      ['z_water', 'z_water', 'z_ice'],
      ['brain', 'z_night', 'music'],
      ['music', 'junk', 'jack_in_the_box'],
      ['brain', 'z_water', 'dolphin'],
      ['brain', 'z_grave', 'flag'],
      ['brain', 'brain', 'big_brain'],
      ['ducky_tube', 'ducky_tube', 'balloon'],
      ['ducky_tube', 'z_night', 'balloon'],
      ['z_zombie', 'z_zombie', 'horde'],
      // ---- zombies
      ['z_zombie', 'brain', 'imp'],
      ['z_zombie', 'flag', 'flag_zombie'],
      ['z_zombie', 'traffic_cone', 'conehead'],
      ['z_zombie', 'bucket', 'buckethead'],
      ['z_zombie', 'pole', 'pole_vaulting'],
      ['z_zombie', 'newspaper', 'newspaper_zombie'],
      ['z_zombie', 'screen_door', 'screen_door_zombie'],
      ['z_zombie', 'football_helmet', 'football_zombie'],
      ['z_zombie', 'music', 'dancing_zombie'],
      ['dancing_zombie', 'z_zombie', 'backup_dancer'],
      ['dancing_zombie', 'horde', 'backup_dancer'],
      ['z_zombie', 'ducky_tube', 'ducky_tube_zombie'],
      ['z_zombie', 'z_water', 'snorkel_zombie'],
      ['z_zombie', 'dolphin', 'dolphin_rider'],
      ['z_zombie', 'jack_in_the_box', 'jack_zombie'],
      ['z_zombie', 'balloon', 'balloon_zombie'],
      ['z_zombie', 'pickaxe', 'digger_zombie'],
      ['z_zombie', 'pogo_stick', 'pogo_zombie'],
      ['z_zombie', 'z_ice', 'zombie_yeti'],
      ['z_zombie', 'bungee_cord', 'bungee_zombie'],
      ['z_zombie', 'ladder', 'ladder_zombie'],
      ['z_zombie', 'vehicle', 'catapult_zombie'],
      ['vehicle', 'z_ice', 'zomboni'],
      ['zomboni', 'horde', 'bobsled_team'],
      ['zomboni', 'z_zombie', 'bobsled_team'],
      ['horde', 'imp', 'gargantuar'],
      ['horde', 'horde', 'gargantuar'],
      ['gargantuar', 'big_brain', 'dr_zomboss'],
      ['vehicle', 'big_brain', 'dr_zomboss'],
    ],
  },
};
